-- ==================================================================
-- 50_templates — spawn area-template overlays (Targeted/Small/Medium/Large)
-- Transparent PNGs generated by tts/assets/src/templates.html.
-- spanHexW = template image span in hex-widths (printed by the generator);
-- a Custom_Tile is 2 world units wide at scale 1.
-- ==================================================================
TEMPLATE_TUNE = 1.0   -- global fudge factor if the grid measures hexes differently

TEMPLATE_SPANS = { targeted = 1.0313, small = 2.6328, medium = 4.3633, large = 6.0938 }

function uiTemplate(player, _, id)
  local key = id:gsub("^tpl_", "")
  local span = TEMPLATE_SPANS[key]
  if span == nil then return end
  local s = span * GRID_X / 2 * TEMPLATE_TUNE
  local ht = Player[player.color] and Player[player.color].getHandTransform()
  local pos = ht and {
    x = ht.position.x + ht.forward.x * 12,
    y = 1.5,
    z = ht.position.z + ht.forward.z * 12,
  } or { x = 0, y = 1.5, z = 0 }
  local tile = spawnObject({
    type = "Custom_Tile",
    position = pos,
    rotation = { 0, 180, 0 },
    scale = { s, 1, s },
    sound = false,
    callback_function = function(o)
      o.setName(key:gsub("^%l", string.upper) .. " area")
      o.setDescription("Area template — snaps to the hex grid. Delete when resolved.")
      o.addTag(TAG_TEMPLATE)
    end,
  })
  tile.setCustomObject({
    image = ASSET_BASE .. "/template_" .. key .. ".png",
    type = 0,           -- square tile, transparent PNG
    thickness = 0.05,
    stackable = false,
  })
end
